name = "miku-call-guide-app"
pages_build_output_dir = "dist"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[vars]
APP_ENV = "production"
GITHUB_DATA_OWNER = "Miku-Events"
GITHUB_DATA_REPO = "miku-call-guide-data"
GITHUB_DATA_BASE_BRANCH = "main"
