// Generated by npm run contracts:emit. Do not edit.
export declare const EVENT_TYPES: readonly ["concert","dj","popup","ticketApplication","ticketGeneralSale","livestream","exhibition","collaboration","announcement","other"];
export type EventType = (typeof EVENT_TYPES)[number];
