// Generated by npm run contracts:emit. Do not edit.
export const EVENT_TYPES = Object.freeze([
  "concert",
  "dj",
  "popup",
  "ticketApplication",
  "ticketGeneralSale",
  "livestream",
  "exhibition",
  "collaboration",
  "announcement",
  "other"
]);
