// Generated by npm run contracts:emit. Do not edit.

export type LocalizedText = Record<string, string | undefined>;

export type EventType = "concert" | "dj" | "popup" | "ticketApplication" | "ticketGeneralSale" | "livestream" | "exhibition" | "collaboration" | "announcement" | "other";

export interface RootManifest {
  schemaVersion: 1;
  generatedAt: string;
  dataVersion: string;
  manifests: {
    callGuide: string;
    eventCalendar: string;
  };
}

export interface CallGuideManifest {
  schemaVersion: 1;
  generatedAt: string;
  dataVersion: string;
  songs: {
    id: string;
    title: {
      [k: string]: string | undefined;
    };
    artist: {
      [k: string]: string | undefined;
    };
    youtubeVideoId: string;
    originalSongId?: string;
    tags: string[];
    path: string;
    status: "published";
    callSummary?: {
      [k: string]: string | undefined;
    };
  }[];
  eventRegistry?: {
    [k: string]:
      | {
          title: {
            [k: string]: string | undefined;
          };
        }
      | undefined;
  };
}

export interface EventCalendarIndex {
  schemaVersion: 1;
  generatedAt: string;
  dataVersion: string;
  availableMonths: string[];
  types: (
    | "concert"
    | "dj"
    | "popup"
    | "ticketApplication"
    | "ticketGeneralSale"
    | "livestream"
    | "exhibition"
    | "collaboration"
    | "announcement"
    | "other"
  )[];
  /**
   * @minItems 1
   */
  typePriority: [
    (
      | "concert"
      | "dj"
      | "popup"
      | "ticketApplication"
      | "ticketGeneralSale"
      | "livestream"
      | "exhibition"
      | "collaboration"
      | "announcement"
      | "other"
    ),
    ...(
      | "concert"
      | "dj"
      | "popup"
      | "ticketApplication"
      | "ticketGeneralSale"
      | "livestream"
      | "exhibition"
      | "collaboration"
      | "announcement"
      | "other"
    )[],
  ];
}

export interface EventCalendarMonth {
  schemaVersion: 1;
  generatedAt: string;
  dataVersion: string;
  month: string;
  events: {
    id: string;
    title: {
      [k: string]: string | undefined;
    };
    type:
      | "concert"
      | "dj"
      | "popup"
      | "ticketApplication"
      | "ticketGeneralSale"
      | "livestream"
      | "exhibition"
      | "collaboration"
      | "announcement"
      | "other";
    /**
     * @minItems 1
     */
    occurrences: [
      (
        | {
            endsAt?: string;
            endsOn?: never;
            id: string;
            label?: {
              [k: string]: string | undefined;
            };
            startsAt: string;
            startsOn?: never;
            timezone: string;
          }
        | {
            endsAt?: never;
            endsOn?: string;
            id: string;
            label?: {
              [k: string]: string | undefined;
            };
            startsAt?: never;
            startsOn: string;
            timezone: string;
          }
      ),
      ...(
        | {
            endsAt?: string;
            endsOn?: never;
            id: string;
            label?: {
              [k: string]: string | undefined;
            };
            startsAt: string;
            startsOn?: never;
            timezone: string;
          }
        | {
            endsAt?: never;
            endsOn?: string;
            id: string;
            label?: {
              [k: string]: string | undefined;
            };
            startsAt?: never;
            startsOn: string;
            timezone: string;
          }
      )[],
    ];
    path: string;
  }[];
}

export interface RuntimeSong {
  schemaVersion: 1;
  dataVersion: string;
  id: string;
  status: "draft" | "reviewed" | "published";
  metadata: {
    title: {
      [k: string]: string | undefined;
    };
    artist: {
      [k: string]: string | undefined;
    };
    /**
     * @minItems 1
     */
    vocal: [string, ...string[]];
    tags: string[];
  };
  catalog?: {
    callSummary: {
      [k: string]: string | undefined;
    };
  };
  youtube: {
    videoId: string;
    originalSongId?: string;
    startOffsetMs: number;
  };
  display: {
    defaultLyricsLanguage: string;
    defaultPronunciationLanguage: string;
    defaultCallLanguage: string;
    autoFirstLyricCountdown?: boolean;
  };
  timing: {
    unit: "ms";
    durationMs: number;
  };
  /**
   * @minItems 1
   */
  lyrics: [
    {
      id: string;
      srtIndex?: number;
      time: string;
      text: {
        [k: string]: string | undefined;
      };
      startMs: number;
      endMs: number;
    },
    ...{
      id: string;
      srtIndex?: number;
      time: string;
      text: {
        [k: string]: string | undefined;
      };
      startMs: number;
      endMs: number;
    }[],
  ];
  callEvents: (
    | {
        activation: {
          mode: "lineActive";
        };
        anchor: {
          targetText: string;
          unit: "grapheme";
          pointChar: number;
          rangeStartChar?: number;
          rangeEndChar?: number;
        };
        cue: {
          kind: "chant" | "penlight" | "custom";
          intensity: "low" | "normal" | "high";
          repeat: number;
        };
        endMs?: never;
        id: string;
        lyricLineId: string;
        markers: {
          point: {
            enabled: boolean;
            style: "pointArrow" | "none";
            direction: "auto" | "up" | "down";
          };
          range: {
            enabled: boolean;
            style: "bracket" | "underline" | "none";
          };
        };
        placement: {
          align: "charAnchor";
          lane: "above" | "below";
          mode: "lyricTrack";
        };
        segments?: never;
        startMs?: never;
        text: {
          [k: string]: string | undefined;
        };
        time?: never;
      }
    | {
        activation: {
          mode: "lineActive";
        };
        anchor?: never;
        cue: {
          kind: "chant" | "penlight" | "custom";
          intensity: "low" | "normal" | "high";
          repeat: number;
        };
        endMs?: never;
        id: string;
        lyricLineId?: never;
        markers?: never;
        placement: {
          align: "charAnchor";
          lane: "above" | "below";
          mode: "lyricTrack";
        };
        /**
         * @minItems 2
         */
        segments: [
          {
            lyricLineId: string;
            part: "start" | "continue" | "end";
            anchor: {
              targetText: string;
              unit: "grapheme";
              pointChar: number;
              rangeStartChar?: number;
              rangeEndChar?: number;
            };
            markers: {
              point: {
                enabled: boolean;
                style: "pointArrow" | "none";
                direction: "auto" | "up" | "down";
              };
              range: {
                enabled: boolean;
                style: "bracket" | "underline" | "none";
              };
            };
          },
          {
            lyricLineId: string;
            part: "start" | "continue" | "end";
            anchor: {
              targetText: string;
              unit: "grapheme";
              pointChar: number;
              rangeStartChar?: number;
              rangeEndChar?: number;
            };
            markers: {
              point: {
                enabled: boolean;
                style: "pointArrow" | "none";
                direction: "auto" | "up" | "down";
              };
              range: {
                enabled: boolean;
                style: "bracket" | "underline" | "none";
              };
            };
          },
          ...{
            lyricLineId: string;
            part: "start" | "continue" | "end";
            anchor: {
              targetText: string;
              unit: "grapheme";
              pointChar: number;
              rangeStartChar?: number;
              rangeEndChar?: number;
            };
            markers: {
              point: {
                enabled: boolean;
                style: "pointArrow" | "none";
                direction: "auto" | "up" | "down";
              };
              range: {
                enabled: boolean;
                style: "bracket" | "underline" | "none";
              };
            };
          }[],
        ];
        startMs?: never;
        text: {
          [k: string]: string | undefined;
        };
        time?: never;
      }
    | {
        activation: {
          mode: "manualTime";
        };
        anchor?: never;
        cue: {
          kind: "chant" | "penlight" | "custom";
          intensity: "low" | "normal" | "high";
          repeat: number;
        };
        endMs: number;
        id: string;
        lyricLineId: null;
        markers: {
          point: {
            enabled: boolean;
            style: "pointArrow" | "none";
            direction: "auto" | "up" | "down";
          };
          range: {
            enabled: boolean;
            style: "bracket" | "underline" | "none";
          };
        };
        placement: {
          align: "timeline";
          lane: "above" | "below";
          mode: "globalTrack";
        };
        segments?: never;
        startMs: number;
        text: {
          [k: string]: string | undefined;
        };
        time: string;
      }
  )[];
  countdownEvents?: {
    id: string;
    time: string;
    startMs: number;
    endMs: number;
  }[];
  notes?: {
    author?: string;
    source?: string;
    reviewComment?: string;
    copyrightNote?: string;
  };
}

export interface RuntimeEvent {
  schemaVersion: 1;
  dataVersion: string;
  id: string;
  status: "draft" | "reviewed" | "published";
  title: {
    [k: string]: string | undefined;
  };
  type:
    | "concert"
    | "dj"
    | "popup"
    | "ticketApplication"
    | "ticketGeneralSale"
    | "livestream"
    | "exhibition"
    | "collaboration"
    | "announcement"
    | "other";
  /**
   * @minItems 1
   */
  occurrences: [
    (
      | {
          endsAt?: string;
          endsOn?: never;
          id: string;
          label?: {
            [k: string]: string | undefined;
          };
          startsAt: string;
          startsOn?: never;
          timezone: string;
        }
      | {
          endsAt?: never;
          endsOn?: string;
          id: string;
          label?: {
            [k: string]: string | undefined;
          };
          startsAt?: never;
          startsOn: string;
          timezone: string;
        }
    ),
    ...(
      | {
          endsAt?: string;
          endsOn?: never;
          id: string;
          label?: {
            [k: string]: string | undefined;
          };
          startsAt: string;
          startsOn?: never;
          timezone: string;
        }
      | {
          endsAt?: never;
          endsOn?: string;
          id: string;
          label?: {
            [k: string]: string | undefined;
          };
          startsAt?: never;
          startsOn: string;
          timezone: string;
        }
    )[],
  ];
  summary?: {
    [k: string]: string | undefined;
  };
  location?: {
    country?: string;
    region?: {
      [k: string]: string | undefined;
    };
    venue?: {
      [k: string]: string | undefined;
    };
  };
  links: {
    official?: string;
    ticket?: string;
    source?: {
      url?: string;
      checkedAt?: string;
    };
    sns?: {
      platform: "x" | "instagram" | "youtube" | "niconico" | "tiktok" | "facebook" | "website" | "other";
      url: string;
      label?: {
        [k: string]: string | undefined;
      };
      embed?: boolean;
    }[];
  };
  tags?: string[];
  visibility?: {
    featured?: boolean;
  };
}

export interface EventRegistry {
  schemaVersion: 1;
  events: {
    [k: string]:
      | {
          title: {
            [k: string]: string | undefined;
          };
        }
      | undefined;
  };
}
