// Generated by npm run contracts:emit. Do not edit.
import type {
  CallGuideManifest,
  EventCalendarIndex,
  EventCalendarMonth,
  EventRegistry,
  RootManifest,
  RuntimeEvent,
  RuntimeSong,
} from "./types.js";

export interface ValidationError {
  instancePath: string;
  schemaPath: string;
  keyword: string;
  params: Record<string, unknown>;
  message?: string;
}

export type ContractValidator<T> = ((value: unknown) => value is T) & {
  errors?: readonly ValidationError[] | null;
};

export declare const validateRootManifest: ContractValidator<RootManifest>;
export declare const validateCallGuideManifest: ContractValidator<CallGuideManifest>;
export declare const validateEventCalendarIndex: ContractValidator<EventCalendarIndex>;
export declare const validateEventCalendarMonth: ContractValidator<EventCalendarMonth>;
export declare const validateRuntimeSong: ContractValidator<RuntimeSong>;
export declare const validateRuntimeEvent: ContractValidator<RuntimeEvent>;
export declare const validateEventRegistry: ContractValidator<EventRegistry>;
